export const elementSeeds = [
  {
    symbol: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    atomicMass: 1.0079,
    group: 1,
    period: 1,
    category: 'Nonmetal',
    phase: 'Gas',
    discoveredBy: 'Henry Cavendish',
    appearance: 'Colorless gas',
    density: 0.00008988,
    meltingPoint: 13.99,
    boilingPoint: 20.27,
  },
  {
    symbol: 'He',
    name: 'Helium',
    atomicNumber: 2,
    atomicMass: 4.0026,
    group: 18,
    period: 1,
    category: 'Noble Gas',
    phase: 'Gas',
    discoveredBy: 'Pierre Janssen',
    appearance: 'Colorless gas',
    density: 0.0001785,
    meltingPoint: 0.95,
    boilingPoint: 4.22,
  },
  // ...more elements
]
