export const orderSeeds = [
  {
    userId: '1',
    totalAmount: 29.99,
    shippingAddress: '123 Main St, Springfield, IL 62701',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '2',
    totalAmount: 39.99,
    shippingAddress: '456 Elm St, Chicago, IL 60601',
    shippingStatus: 'shipped',
    orderStatus: 'completed',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '3',
    totalAmount: 49.99,
    shippingAddress: '789 Oak St, Madison, WI 53703',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '4',
    totalAmount: 19.99,
    shippingAddress: '101 Pine St, Peoria, IL 61602',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '5',
    totalAmount: 59.99,
    shippingAddress: '202 Birch St, Rockford, IL 61101',
    shippingStatus: 'shipped',
    orderStatus: 'completed',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '6',
    totalAmount: 89.99,
    shippingAddress: '303 Maple St, St. Louis, MO 63101',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '7',
    totalAmount: 99.99,
    shippingAddress: '404 Cedar St, Kansas City, MO 64101',
    shippingStatus: 'shipped',
    orderStatus: 'completed',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '8',
    totalAmount: 29.99,
    shippingAddress: '505 Walnut St, Des Moines, IA 50309',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '9',
    totalAmount: 59.99,
    shippingAddress: '606 Pine St, Omaha, NE 68102',
    shippingStatus: 'shipped',
    orderStatus: 'completed',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    userId: '10',
    totalAmount: 79.99,
    shippingAddress: '707 Oak St, Lincoln, NE 68508',
    shippingStatus: 'pending',
    orderStatus: 'processing',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]
