export const orderSeeds = [
  {
    user_id: '1',
    total_amount: 29.99,
    shipping_address: '123 Main St, Springfield, IL 62701',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '2',
    total_amount: 39.99,
    shipping_address: '456 Elm St, Chicago, IL 60601',
    shipping_status: 'shipped',
    order_status: 'completed',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '3',
    total_amount: 49.99,
    shipping_address: '789 Oak St, Madison, WI 53703',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '4',
    total_amount: 19.99,
    shipping_address: '101 Pine St, Peoria, IL 61602',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '5',
    total_amount: 59.99,
    shipping_address: '202 Birch St, Rockford, IL 61101',
    shipping_status: 'shipped',
    order_status: 'completed',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '6',
    total_amount: 89.99,
    shipping_address: '303 Maple St, St. Louis, MO 63101',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '7',
    total_amount: 99.99,
    shipping_address: '404 Cedar St, Kansas City, MO 64101',
    shipping_status: 'shipped',
    order_status: 'completed',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '8',
    total_amount: 29.99,
    shipping_address: '505 Walnut St, Des Moines, IA 50309',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '9',
    total_amount: 59.99,
    shipping_address: '606 Pine St, Omaha, NE 68102',
    shipping_status: 'shipped',
    order_status: 'completed',
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    user_id: '10',
    total_amount: 79.99,
    shipping_address: '707 Oak St, Lincoln, NE 68508',
    shipping_status: 'pending',
    order_status: 'processing',
    created_at: new Date(),
    updated_at: new Date(),
  },
]
