export const productSeeds = [
  {
    name: 'Bella + Canvas 3001 Unisex T-Shirt Front Print',
    description: `Seeking a T-shirt that's as stylish as it is comfortable? Meet the Bella + Canvas 3001 Jersey Tee, your new go-to for effortless chic. This superior quality T-shirt is made from premium cotton, offering a luxurious feel and impeccable fit. Whether you're out with friends or enjoying a laid-back day, our T-shirt ensures both style and comfort.`,
    material: 'Cotton',
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    colors: ['White', 'Black'],
    price: 11.5,
    empire_builder_price: 7.5,
    suggested_sales_price: 19.99,
    estimated_profit: 8.49,
    production_time: '3-5 business days',
    product_care_instructions: [
      'Machine wash cold',
      'Do not dry clean',
      'Tumble dry low',
      'No chemical cleaners',
    ],
    style: 'Crew neck, short sleeves, side seamed, unisex fit',
    print_type: 'Direct-to-Garment (DTG) printing for lasting colors',
    print_location: 'Front only',
  },
  {
    name: 'Bella + Canvas 3001Y Youth T-Shirt',
    description: `Give your little one the best in comfort and style with the Bella + Canvas 3001Y Youth T-Shirt! With a classic fit, and a comfy crew neck, it's a wardrobe essential. Made from soft cotton, it's perfect for endless playtime!`,
    material: '100% Airlume combed and ring-spun cotton',
    sizes: ['S', 'M', 'L'],
    colors: ['White', 'Black'],
    price: 11.5,
    empire_builder_price: 7.5,
    suggested_sales_price: 19.99,
    estimated_profit: 8.49,
    production_time: '3-5 business days',
    product_care_instructions: [
      'Machine wash cold',
      'Do not dry clean',
      'Tumble dry low',
      'No chemical cleaners',
    ],
    style: 'Crew neck, side seamed, unisex fit',
    print_type: 'Direct-to-Garment (DTG) printing for lasting colors',
    print_location: 'Front only',
  },
]
